GET http://localhost:8080/owners?page=1&size=5
Content-Type: application/json

###
POST http://localhost:8080/owners
Content-Type: application/json

{
  "firstname": "",
  "lastname": "",
  "address": "",
  "pets": [
    {
      "name": "",
      "animalType": "",
      "dateOfBirth": ""
    }
  ]
}
